#!/bin/bash

Green='\033[0;32m'
Yellow='\033[1;33m'
NC='\033[0m' # no color


printf "${Yellow}Create_package <WS> <NAME> \n"
printf "The package is created with the dependecies of std_msgs rospy roscpp ${NC} \n"

cd $1/catkin_ws/src &&
catkin_create_pkg $2 std_msgs rospy roscpp &&
cd $1/catkin_ws &&
catkin_make &&

printf "${Green}ROS package created sucesfully"
