#!/bin/bash
#Docker installation


#echo color table
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT_GRAY='\033[0;37m'
DARK_GRAY='\033[1;30m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHT_BLUE='\033[1;34m'
LIGHT_PURPLE='\033[1;35m'
LIGHT_CYAN='\033[1;36m'
WHITE='\033[1;37m'
NC='\033[0m' #no color


echo -e "${CYAN}SETUP:apt-get update ${NC}"
sudo apt-get update &&
echo -e "${CYAN}SETUP:sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D ${NC}"
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D &&

echo -e "${CYAN}SETUP:sudo apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'${NC}"
sudo apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main' &&

echo -e "${CYAN}SETUP:sudo apt-get update ${NC}"
#apt-cache policy docker-engine
sudo apt-get update &&
#printf "${Cyan}apt-cache policy docker-engine \n"
#apt-cache policy docker-engine &&

echo -e "${CYAN}sudo apt-get install -y docker-engine ${NC}"
sudo apt-get install -y docker-engine &&

#echo "SETUP:sudo systemctl status docker"
#sudo systemctl status docker && 
echo -e "${GREEN}SETUP:Docker installed Sucessfully"
