#!/bin/bash

#source:http://wiki.ros.org/melodic/Installation/Ubuntu

#echo color table
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT_GRAY='\033[0;37m'
DARK_GRAY='\033[1;30m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHT_BLUE='\033[1;34m'
LIGHT_PURPLE='\033[1;35m'
LIGHT_CYAN='\033[1;36m'
WHITE='\033[1;37m'
NC='\033[0m' #no color

echo -e "${YELLOW} :::ROS Melodic its only supported by Ubuntu 18.04 ${NC}"

sudo apt-get update &&

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list' &&

sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654 &&

curl -sSL 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC1CF6E31E6BADE8868B172B4F42ED6FBAB17C654' | sudo apt-key add - &&

sudo apt-get update &&

sudo apt-get install  python-pip &&
sudo pip install -U rosdep rospkg &&

sudo apt install -y ros-melodic-desktop-full &&
sudo rosdep init &&
rosdep update &&
echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc &&
source ~/.bashrc &&
source /opt/ros/melodic/setup.bash &&
sudo apt install -y python-rosinstall python-rosinstall-generator python-wstool build-essential &&

echo -e "${GREEN} :::ROS Melodic has been successfully installed"




